open-source-labs/Svelvet

- package-lock.json
- src/lib/ConnectionLine/index.svelte
- src/lib/Containers/EdgeRenderer/index.svelte
- src/lib/Containers/EdgeRenderer/utils.ts
- src/lib/Containers/Svelvet/index.svelte
- src/lib/Edges/BaseEdge.svelte
- src/lib/Edges/EdgeAnchor.svelte
- src/lib/Edges/EdgeText.svelte
- src/lib/Edges/SimpleBezierEdge.svelte
- src/lib/Edges/wrapEdge.svelte
- src/lib/Nodes/DefaultNode/index.svelte
- src/lib/Nodes/InputNode/index.svelte
- src/lib/Nodes/OutputNode/index.svelte
- src/lib/stores/store.ts
- src/routes/index.svelte
- svelte.config.js
- vite.config.js
Co-authored-by: Alexander Zambrano <azambran21@users.noreply.github.com>
Co-authored-by: Aaron <awillettnyc@users.noreply.github.com>
Co-authored-by: anu (they/them) <anulepau@users.noreply.github.com>
> Implemented a store and rendered the bezier edges

- .github/workflows/main.yml
> add Deployment action

- src/lib/Containers/GraphView/index.svelte
- src/lib/Containers/Svelvet/index.svelte
- src/lib/Nodes/index.svelte
- src/lib/stores/store.ts
- src/routes/docs/pan-and-zoom.svelte
- src/routes/playground.svelte
I'm trying to use multiple Svelvet's on one page and I think this might be the problem.
I tried installing from my fork in GitHub and it was failing so I struggled to test this properly. Very happy to get feedback on this one.
> Add ability to have multiple graph views on one page

- src/lib/Containers/GraphView/index.svelte
- src/lib/Nodes/index.svelte
- src/lib/stores/store.ts
- src/lib/types/types.ts
- src/routes/playground.svelte
Add the ability to specify a callback for nodes when clicked.
> Add click callback function for nodes

- package-lock.json
- src/routes/docs/custom-nodes.svelte
- src/routes/docs/node-grouping.svelte
Updated node-grouping webpage for user reference.
> Node grouping

- src/components/DocsSideNav.svelte
- src/components/Footer.svelte
- src/components/MobileDocsNav.svelte
- src/routes/docs/CSS-Background.svelte
- src/routes/docs/HTML-Docs.svelte
- src/routes/docs/snap-to-grid.svelte
- fixed minor typos
- added a new page & associated routes under docs
- added code block in HTML documentation so that users can better understand declaration
> Added documentation explaining HTML Enhancements

- package-lock.json
- package.json
- src/lib/index.js
- removed node.env from dependencies
- thank you @FractalHQ for bringing this to our attention
- this will resolve Github Issue #142 
- previously resolved Github Issue #140 
- site has already been updated to restore touch functionality
> Removing node.env

- cypress/e2e/drag_n_drop.cy.ts
- package-lock.json
- src/repl/CodeMirror.svelte
- src/routes/docs/Initial-Zoom-Location.svelte
- supabase_env
-added props (initialZoom, initialLocation, minimap={true} to default code on REPL
--> to better showcase new functionality
- re-added supabase_env instructions (previously missing)
- minor edits to cypress tests to changes in testing playground??
> Details cleanup

- NPM Package/svelvet/Containers/Svelvet/index.svelte
- NPM Package/svelvet/package.json
- package-lock.json
- package.json
added back afterUpdate method to Svelvet component to fix issue with dynamic re-renders
> re-add afterUpdate in svelvet component

- src/components/TopNav.svelte
> changed 5.0.7 to 6.0.0 in navbar

- src/lib/container/README.md
- src/lib/docs/CHANGELOG.md
- src/lib/docs/DESIGN_PATTERNS.md
- src/lib/docs/DOCUMENTATION.md
- src/lib/docs/README.md
- src/lib/docs/Tutorials.md
- tests/unit/BaseEdge.test.ts
> Fix: BaseEdge tests commented out

- src/lib/docs/Tutorials.md
- src/routes/playground/index.svelte
Repl appears to be incompatible with Svelvet6 due to different store. Replaced with StackBlitz until issue is resolved
> FIX: replaces repl with stackblitz

- src/routes/docs/CSS-Background.svelte
- src/routes/docs/basic-usage.svelte
- src/routes/docs/boundary.svelte
- src/routes/docs/core-concepts.svelte
- src/routes/docs/custom-edges.svelte
CodeSandbox is going through some issues. Changing to StackBlitz so demos work during launch
> FIX: changed demos from codeSandbox to stackBlitz

- .gitignore
- package-lock.json
- package.json
- src/components/DocsSideNav.svelte
- src/components/Footer.svelte
- src/lib/container/views/GraphView.svelte
- src/lib/edges/views/Edges/BaseEdge.svelte
- src/lib/nodes/views/Node.svelte
- src/lib/package.json
- src/routes/docs/editEdge.svelte
Fix: node touchmove no longer fire on entire window just the node
Fix: baseEdge on:keypress fixes the accessibility warning in repl
> Fix: svelvet.io site works with mobile

- package-lock.json
- package.json
- src/lib/collapsible/controllers/util.ts
- src/lib/container/controllers/middleware.ts
- src/lib/container/views/Svelvet.svelte
- src/lib/edges/models/Edge.ts
- src/lib/index.js
- src/lib/interactiveNodes/views/PotentialAnchor.svelte
- src/lib/package.json
- src/lib/store/controllers/storeApi.ts
- src/lib/store/controllers/util.ts
- src/lib/store/types/types.ts
- src/lib/types/README.md
- src/lib/types/types.ts
- src/routes/dev/compatibility-4-typescript/index.svelte
- src/routes/docs/typescript.svelte
- tests/unit/Anchor.test.ts
- tests/unit/Node.test.ts
- tests/unit/ResizeNode.test.ts
- tests/unit/SimpleBezierEdge.test.ts
- tests/unit/SmoothStepEdge.test.ts
Type Node, Edge, renamed to UserNodeType, UserEdgeType
> DOC: updates documentation for user types

- src/lib/components/Anchor/Anchor.svelte
> Fix `on:connection` not firing, fixes #261

- src/lib/containers/Graph/Graph.svelte
- tests/inputs/test.ts
> fix: keydown listener was not returning properly when input elements were focused

- package.json
- src/example-components/Percent.Svelte
- src/lib/components/Anchor/Anchor.svelte
- src/lib/components/Node/InternalNode.svelte
- src/lib/components/Resizer/Resizer.svelte
- src/lib/containers/Graph/Graph.svelte
- src/routes/+page.svelte
feat: custom nodes that change dimensions dynamically are now supported
> feat: nodes can now be resized from all sides

- src/lib/containers/Svelvet/Svelvet.svelte
> fix: fixedZoom was not public on the Svelvet component

- src/lib/components/Anchor/Anchor.svelte
The library should not import from the documentation itself.
Fixes #416
> remove wrong import

- .eslintrc.cjs
- package.json
- src/example-components/CustomEdge.svelte
- src/lib/components/Anchor/Anchor.svelte
- src/lib/components/Drawer/Drawer.svelte
- src/lib/components/Edge/Edge.svelte
- src/lib/containers/Svelvet/Svelvet.svelte
- src/routes/edge-delete/+page.svelte
@briangregoryholmes I think this piece was lost when resolving merge conflicts. I added it back here. Also, the markdown docs are updated in the repo but it seems like maybe they need to be redeployed fyi.
> Passing the hovering prop to the default slot.

- docs/components/node.mdx
Correct function call to set.bgColor
> Correct function call to set.bgColor

- package-lock.json
- package.json
- src/lib/index.js
- src/lib/utils/savers/reloadStore.ts
- src/lib/utils/savers/saveStore.ts
**Description**
Minor fix from 10.0.0 to 10.0.2
Removed flatten and flatted libraries causing npm not install svelvet.
Imported + Exported ContrastTheme component into index.js.
**Testing Instructions**
N/A
**Checklist**
N/A
**Additional Notes, Images, etc.**
N/A
Co-authored-by: Mayson Lee <[mayson0717@gmail.com](mailto:mayson0717@gmail.com)>
Co-authored-by: Isaac Bocage <[ibocage1@gmail.com](mailto:ibocage1@gmail.com)>
Co-authored-by: Julian Bos <[julianb1212@gmail.com](mailto:julianb1212@gmail.com)>
Co-authored-by: Solomon Moon <[chochobo91@gmail.com](mailto:chochobo91@gmail.com)>
> pre-launch last minute changes

- README.md
- package.json
Minor fixes to README blog linked to Svelvet v10 article and package.json version update.
> Minor fixes to README and package.json
